# 定義 API 版本與資源類型
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp        # 部署物件的名稱
  labels:
    app: vproapp       # 部署物件本身的標籤
spec:
  replicas: 1          # 指定運行 1 個 Pod 副本
  selector:
    matchLabels:
      app: vproapp     # 標籤選擇器，用來管理帶有此標籤的 Pod
  template:
    metadata:
      labels:
        app: vproapp   # 設定 Pod 的標籤，必須與 selector 匹配
    spec:
      containers:
      - name: vproapp
        image: vprocontainers/vprofileapp # 應用程式的鏡像檔案
        imagePullPolicy: Always           # 每次啟動都重新從鏡像倉庫拉取最新鏡像
        ports:
        - name: vproapp-port
          containerPort: 8080             # 容器內部監聽的埠號

      # 初始化容器：在主容器啟動前執行，若執行失敗，主容器不會啟動
      initContainers:
      # 1. 檢查資料庫是否就緒
      - name: init-mydb
        image: busybox
        command: ['sh']
        # 循環執行 nslookup 檢查 vprodb 服務的 DNS 是否能解析
        # $(cat ...) 部分會自動取得目前的 Namespace，拼接成完整的內部域名
        args: ['-c', 'until nslookup vprodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
      
      # 2. 檢查快取伺服器是否就緒
      - name: init-memcache
        image: busybox
        command: ['sh']
        # 同樣透過 nslookup 檢查 vprocache01 服務是否已在網路中就緒
        args: ['-c', 'until nslookup vprocache01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for memcache; sleep 2; done;']
