# 指定 API 版本與資源類型
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp        # Deployment 的名稱
  labels:
    app: vproapp       # 標註此 Deployment 的 Label
spec:
  replicas: 1          # 定義 Pod 的副本數量為 1
  selector:
    matchLabels:
      app: vproapp     # Selector 用於尋找並管理帶有此 Label 的 Pod
  template:
    metadata:
      labels:
        app: vproapp   # 設定 Pod 的 Label，必須符合上面的 Selector
    spec:
      containers:
      - name: vproapp
        image: vprocontainers/vprofileapp # 應用程式的 Container Image
        imagePullPolicy: Always           # 每次部署時強制從 Registry 下載最新版本
        ports:
        - name: vproapp-port
          containerPort: 8080             # Container 內部監聽的 Port

      # Init Containers：在主 Container 啟動前的預檢查機制
      initContainers:
      # 第一個 Init Container：檢查 Database 是否就緒
      - name: init-mydb
        image: busybox
        command: ['sh']
        # 透過 nslookup 檢查 vprodb Service 的 DNS 解析
        # 利用 cat 指令從 Service Account 檔案動態取得目前的 Namespace
        args: ['-c', 'until nslookup vprodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
      
      # 第二個 Init Container：檢查 Memcached 是否就緒
      - name: init-memcache
        image: busybox
        command: ['sh']
        # 循環檢查 vprocache01 Service 是否已在內部網路生效
        args: ['-c', 'until nslookup vprocache01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for memcache; sleep 2; done;']
