# API Version 與 Resource Type
apiVersion: v1
kind: Secret
metadata:
  name: app-secret         # Secret 名稱，供 Deployment 中的 secretKeyRef 引用
type: Opaque               # 預設類型，用於儲存任意格式的二進制數據 (Arbitrary Data)
data:
  # 注意：data 欄位中的值必須經過 Base64 Encoding
  db-pass: dnByb2RicGFzcw==  # 明文為 "vprodbpass" 的 Base64 編碼
  rmq-pass: Z3Vlc3Q=         # 明文為 "guest" 的 Base64 編碼
